- js-extensions/packages/feedback/lib/index.tsx
- js-extensions/packages/feedback/lib/modal.tsx
- js-extensions/packages/feedback/lib/renderer.tsx
- js-extensions/packages/feedback/lib/selection.tsx
- js-extensions/packages/feedback/lib/utils.ts
This PR appends the current page path (`window.location.pathname`) to the `extra` field stored in local storage. This value is used to filter which highlights should be rendered, fixing the current issue where all highlights are shown regardless of which page they were created.
The `extra` field is still a string, but instead of only being the text the user submitted as feedback, it's now a stringified object with a `text` attribute (user's feedback) and `page` attribute.
> Only show feedback on page given

- js-extensions/packages/feedback/feedback.scss
- js-extensions/packages/feedback/lib/modal.tsx
- js-extensions/packages/feedback/lib/renderer.tsx
- js-extensions/packages/feedback/lib/selection.tsx
- js-extensions/packages/feedback/lib/tooltip.tsx
This PR fixes a couple issues when using the new feedback feature on iOS (safari).
This turned out to be an issue with the listener attached to the clickable divs. The existing `onClick` listeners weren't firing, so I added `onTouchStart` listeners to open the modal and remove feedback on mobile. I did a similar thing within `tooltip.tsx`, which wasn't correctly tracking hovers on mobile since the listeners were mouse-specific.
I guess webkit has a weird preset where, if the input has a `font-size` < 16px, it zooms in for you. Fixed this by making the fonts in the modal 16px.
> Fix issues with tooltip/feedback not working iOS

- js-extensions/packages/feedback/feedback.scss
- js-extensions/packages/feedback/lib/tooltip.tsx
This PR re-introduces a previously-removed transparent border between the highlighted text and tooltip. This adds some spacing between the two but also _very slightly_ changes the look of the tooltip because the border radius no longer exists on the side facing the highlight.
> Bring back transparent border for feedback tooltip

- js-extensions/packages/feedback/lib/renderer.tsx
Something I missed in #3 - tooltips for existing feedback don't have a `placement` and thus don't have the `pop-top` or `pop-bottom` classes which add the transparent border:
After this PR:
> Add transparent border to existing feedback tooltip

- js-extensions/packages/feedback/lib/modal.tsx
- js-extensions/packages/feedback/lib/renderer.tsx
- js-extensions/packages/feedback/lib/selection.tsx
- js-extensions/packages/feedback/lib/utils.ts
This PR modifies the logging done by the feedback system. It moves all logging into web-highlighter's "hooks" (`Highlighter.event.CREATE` and `Highlighter.event.REMOVE`). Instead of logging just the text from the user and the page from which they logged, the entire `HighlightSource` (used to reconstruct the highlight and render on the page) is logged. Additionally, the ID of deleted highlights is logged.
Here's an example of what `feedback.log` will look like:
```json
{"commitHash":"ad0737f858949d7afbecc584b89f6ed8b84b3444\n","payload":{"action":"create","data":{"__isHighlightSource":{},"endMeta":{"parentIndex":5,"parentTagName":"P","textOffset":20},"extra":{"page":"/","text":"My feedback! (soon to be deleted)"},"id":"bfe1d4da-9de1-43d8-9a05-05a1203383cf","startMeta":{"parentIndex":5,"pare …
```
> Log more information about feedback + log removed highlights

- js-extensions/jest-puppeteer.config.js
- js-extensions/package.json
The jest-puppeteer tests have been flaky recently due to timeouts waiting for the rust-book server starting. It looks like this can be caused by the [environment not allocating enough threads](https://github.com/smooth-code/jest-puppeteer#running-puppeteer-in-ci-environments) to run puppeteer and the server in parallel. Using this new jest command will force the tests to run in a single thread.
> Run jest serially to avoid CI timeout

- src/ch04-03-fixing-ownership-errors.md
Can't `push_str` on immutable variable. The example doesn't compile. I believe just adding `mut` to:
```rust
let full = name.join(" ");
```
Fixes the issue.
> Fix example so it compiles

- src/ch05-01-defining-structs.md
typo fixed: 
PS: I am really enjoying reading this version of the Rust book. I love the code animations of R,W,O for the borrow checker.
> minor typo fix: Update ch05-01-defining-structs.md

- src/ch01-01-installation.md
- src/title-page.md
If the docs tell people that a specific version of Rust is required, give them the command to show their Rust version.
Include a command prompt in all commands.
%PATH% is a Windows construct and shouldn't be used generically to describe the PATH environment variable, which you call a system variable.
> Added rust version to intro page; added missing command prompt to Linux/macOS command; fixed incorrect reference to PATH

- src/ch05-03-method-syntax.md
From line 145  to 146, I think the definition of Associated function doesn't make complete sense without the addition I made to it.
> Doc: added two words to make complete sense

- src/ch04-02-references-and-borrowing.md
> For example, say we tried to drop string while holding a reference to it: 
Should be:
> For example, say we tried to drop **a** string while holding a reference to it:
> Fix grammar error

- src/ch17-03-oo-design-patterns.md
It's unclear what it means for an assertion to be an empty string.
> Fix "be" -> "being"

- src/ch04-02-references-and-borrowing.md
Fix a typo to match the example above it. 'v.push(4)' -> 'vector.push(4)'
> Fix the typo in ch04-02

- src/ch18-02-refutability.md
The old example is wrong. It would be refutable if the expression becomes `if let ...`, but it in the old case, with just a `let ...` it is irrefutable. That this example is refutable is contradicted by the next paragraph. It also gives a compiler error when given by itself (refutable pattern in local binding. pattern `&[]` not covered. note: `let` bindings require an "irrefutable pattern", like a `struct` or an `enum` with only one variant. The error specifically points to this same chapter in docs.rust-lang.org, which does not include these examples.
> Refutability 18-02 example fix

- quizzes/ch04-01-ownership-sec2-moves.toml
Chapter 04.01. - What is Ownership? - Quiz at the bottom of the page, Question 3
Fix typo.
> ... or select "None of the above" **is** none of these snippets would cause undefined behavior
- Is: `is`
- Should be: `if`
> Fix typo in Quiz ch04-01-ownership-sec2-moves.toml

- src/ch04-02-references-and-borrowing.md
> Moved heap data principle: if a variable x moves ownership of heap data to another variable y, then x cannot be used after the move.
> Box deallocation principle (fully correct): If a variable owns a box, when Rust deallocates the variable's frame, then Rust deallocates the box's heap memory.
The moved heap data principle emphasizes the fact that we cannot use a variable that was moved.
The box deallocation principle emphasizes that a variable's heap memory gets deallocated if the variable owned the box (pointing to the heap memory).
The context of this paragraph is in line with the Box Deallocation Principle.
> Replace statement "Moved Heap Data Principle" wit "Box Deallocation Principle".

- src/ch04-05-ownership-recap.md
Hi 👋  I noticed a few minor typos as I was reading this page and wanted to contribute a little back. Thanks,
Changes:
- Consistently use `words` rather than `word`
- Consistently use array rather than list or array
> Chapter 4 | Ownership Recap - Fix small typo

- src/ch05-01-defining-structs.md
Leftover from 08c63f2 ([diff](https://github.com/cognitive-engineering-lab/rust-book/commit/08c63f2df5855d5f88666b40a21bd4c7fda13f01#diff-8c830352f965caab3816447cd5084a67d13142c8a702d728bc412fc075601980R119)) & b0ffa34 ([diff](https://github.com/cognitive-engineering-lab/rust-book/commit/b0ffa3494cd61f407b316863ac892e2784adbb38#diff-8c830352f965caab3816447cd5084a67d13142c8a702d728bc412fc075601980R200))
> Fix broken link to Copying vs. Moving Out of a Collection in ch05-01

- src/ch04-03-fixing-ownership-errors.md
> Fix a typo ch04-03-fixing-ownership-errors.md

- src/ch03-03-how-functions-work.md
The contrastive relation removed. The contrast here seems a bit confusing, as there is no clear logical connection between the preceding and following sentences.
> Fix a word in ch03-03-how-functions-work.md

- quizzes/ch17-05-design-challenge-references.toml
The definition of `asset` returns `()`, which doesn't seem to be intended. The definition of `another_asset` would result in a syntax error from the missing semicolon.
> fix typo in code snippet

- quizzes/ch13-01-closures-sec2.toml
The functions name is `postprocess`, so it should be `postprocess` as well in the provided context.
> Fix context of quiz on closures

- src/ch10-03-lifetime-syntax.md
I'm guessing there used to be two different reference examples here and one was removed, but now there's a subject-verb number mismatch. (Maybe the sentence should be rewritten entirely though.)
> Grammar fix in lifetime syntax

- listings/ch17-async-await/listing-17-11/src/main.rs
In listings 17-10 , 17-12  and 17-13 , the 
```rust
let (tx, mut rx) = trpl::channel(); 
```
is not left out, but in listing 17-11 it IS.
I propose adding the `tx` and `rx` variables creation to listing 17-11 , so it matches the way the other listings are written.
> Change location of ANCHOR: futures to match Listings 17-10 , 17-12 and 17-13

- listings/ch17-async-await/listing-17-31/src/main.rs
- listings/ch17-async-await/listing-17-32/src/main.rs
Hi! I saw these two listings missing the anchors, so they were showing 
```rust
extern crate trpl; // required for mdbook test
```
Are the anchor names ok? I couldn't find info on any standart naming about them
> Add anchors to listings 17-31 and 17-32 in order to hide `extern crate trpl;`
